before_script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm install codacy-coverage --save; fi'
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run test:codacy-coverage; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run test; fi'
sudo: required
language: node_js
node_js:
  - 8
  - lts/*
  - node